version: "3.7"
services:
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: services-api:latest
    restart: always

    depends_on:
      - db
    ports:
      - "4000:4000"
